import { SiteLayout } from "@/components/site/SiteLayout";
import { Seo } from "@/components/site/Seo";
import { siteConfig } from "@/lib/siteConfig";

export default function PrivacyPolicy() {
  return (
    <SiteLayout>
      <Seo
        title="Privacy Policy"
        description="How Aisom collects, uses and protects personal information under POPIA."
        path="/privacy-policy"
      />

      <section className="wrap py-20">
        <h1 className="text-[26px] text-slate md:text-[34px]">Privacy policy</h1>
        <p className="mt-4 text-ash">Aisom Systems (Pty) Ltd, registration number 2026/234071/07, trading as Aisom ("Aisom", "we", "us", "our"), respects your privacy. This Privacy Policy explains how we collect, use, disclose, store and protect personal information when you use our website (aisom.co.za), our services, or otherwise interact with us, in accordance with the Protection of Personal Information Act 4 of 2013 (POPIA) and the Electronic Communications and Transactions Act 25 of 2002.</p>

        <h2 className="mt-8 text-[18px] text-slate">1. Information we collect</h2>
        <p className="mt-2 text-ash">Depending on how you interact with us, we may collect:</p>
        <ul className="mt-2 list-disc pl-6 text-ash">
          <li>Contact details you submit, such as your name, business name, email address and phone number.</li>
          <li>Enquiry details, including package interest, existing website URL, project description and the page where you contacted us.</li>
          <li>Your separate opt-in record if you subscribe to email updates.</li>
          <li>Business information: details you provide about your business for the purpose of building your website (services, pricing, images, logos, descriptions).</li>
          <li>Project correspondence and files you choose to send us.</li>
          <li>Technical information generated by essential site operation and, only if you allow it, optional analytics about site usage.</li>
        </ul>

        <h2 className="mt-6 text-[18px] text-slate">2. How we use your information</h2>
        <p className="mt-2 text-ash">We use personal information for purposes including responding to enquiries and preparing quotes or proposals; providing, delivering and supporting our website design and development services; processing payments and issuing invoices; communicating with you about your project, account, or support requests; sending marketing communications where you have opted in; improving our website and services through analytics; and complying with legal, tax and regulatory obligations.</p>

        <h2 className="mt-6 text-[18px] text-slate">3. Lawful basis for processing</h2>
        <p className="mt-2 text-ash">We process personal information on one or more of the following bases: your consent; necessity to conclude or perform a contract with you; compliance with a legal obligation; or our legitimate business interests, provided these do not override your rights and interests as a data subject.</p>

        <h2 className="mt-6 text-[18px] text-slate">4. Sharing of information</h2>
        <p className="mt-2 text-ash">We do not sell or rent personal information. Form submissions are stored using Supabase. If email notifications are enabled, enquiry details may be processed by our email provider. Optional website analytics are provided by PostHog only after you allow analytics. We may also share information with professional advisors or authorities where required by law, subject to appropriate protections.</p>

        <h2 className="mt-6 text-[18px] text-slate">5. Cookies & tracking technologies</h2>
        <p className="mt-2 text-ash">Optional PostHog analytics remain off unless you select “Allow analytics” in the privacy choices notice. Your choice is stored in this browser so it can be remembered; you can change it using Cookie settings in the footer. You may also clear site data through your browser settings.</p>

        <h2 className="mt-6 text-[18px] text-slate">6. Data security</h2>
        <p className="mt-2 text-ash">We implement appropriate technical and organisational measures to protect personal information, including access controls, secure hosting, and encrypted connections (HTTPS/SSL). No method of transmission or storage is completely secure and we cannot guarantee absolute security.</p>

        <h2 className="mt-6 text-[18px] text-slate">7. Data retention</h2>
        <p className="mt-2 text-ash">We retain personal information only for as long as necessary to fulfil the purposes described in this Policy, to comply with legal or accounting obligations, or to resolve disputes, after which it is securely deleted or anonymised.</p>

        <h2 className="mt-6 text-[18px] text-slate">8. Cross-border transfers</h2>
        <p className="mt-2 text-ash">Where personal information is transferred to or processed by service providers outside South Africa, we take reasonable steps to ensure such recipients provide an adequate level of protection consistent with POPIA, including contractual safeguards.</p>

        <h2 className="mt-6 text-[18px] text-slate">9. Your rights as a data subject</h2>
        <p className="mt-2 text-ash">Subject to POPIA, you have the right to be informed, access your personal information, request correction or deletion, object to processing (including for direct marketing), withdraw consent where processing is based on consent, and lodge a complaint with the Information Regulator of South Africa.</p>

        <h2 className="mt-6 text-[18px] text-slate">10. Children's privacy</h2>
        <p className="mt-2 text-ash">Our website and services are not directed at children under 18. If we become aware that we have inadvertently collected personal information from a child without appropriate consent, we will take reasonable steps to delete it.</p>

        <h2 className="mt-6 text-[18px] text-slate">11. Changes to this policy</h2>
        <p className="mt-2 text-ash">We may update this Privacy Policy from time to time. We will post the updated Policy on this page with a revised "Last Updated" date. Continued use of our website or services after such changes constitutes acceptance of the updated Policy.</p>

        <h2 className="mt-6 text-[18px] text-slate">12. Contact & Information Officer</h2>
        <p className="mt-2 text-ash">Aisom Systems (Pty) Ltd · Reg. {siteConfig.registration}<br />Privacy enquiries: <a className="underline" href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a><br />Postal address: {siteConfig.address.street}, {siteConfig.address.locality}, {siteConfig.address.region} {siteConfig.address.postalCode}, South Africa</p>

        <p className="mt-8 text-[13px] text-ash">Last updated: 4 October 2026</p>
      </section>
    </SiteLayout>
  );
}
